version: "3.9"
services:
  db:
    image: postgres:14.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/postgresql/data
        volume:
          nocopy: true

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_HOST: db
      DATABASE_PASSWORD: postgres
    tty: true
    stdin_open: true
    depends_on:
      - db
    volumes:
      - type: bind
        source: .
        target: /app
      - type: volume
        source: gem-data
        target: /app/vendor/bundle
        volume:
          nocopy: true

  web:
    image: nginx:1.21
    ports:
      - 8080:80
    depends_on:
      - app
    volumes:
      - type: bind
        source: ./nginx/default.conf
        target: /etc/nginx/conf.d/default.conf

volumes:
  db-data:
  gem-data:
